#!/usr/bin/env python3
"""Split reference/raw_export.json into per-sheet CSVs + a sheet inventory.

Run from the repo root:  python3 scripts/split_export.py

Reads the combined export bundle (code + spreadsheet snapshot) produced by
`exportToGitHub` / `exportEverythingToJson` in apps_script/JSON EXPORT.gs and
regenerates:
  - spreadsheet/<Sheet Name>.csv   (displayed values, one file per tab)
  - spreadsheet/README.md          (inventory table with live row counts)

It intentionally does NOT touch reference/raw_export.json or apps_script/.
"""
import csv
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT = os.path.join(REPO_ROOT, "reference", "raw_export.json")
SHEET_DIR = os.path.join(REPO_ROOT, "spreadsheet")


def safe_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9 _()?-]", "_", name).strip()


def main() -> int:
    if not os.path.exists(EXPORT):
        print(f"error: {EXPORT} not found", file=sys.stderr)
        return 1

    with open(EXPORT) as fh:
        bundle = json.load(fh)

    ss = bundle.get("spreadsheet") or {}
    sheets = ss.get("sheets", [])
    os.makedirs(SHEET_DIR, exist_ok=True)

    inventory = []
    for sheet in sheets:
        name = sheet["name"]
        rows = sheet.get("rows", [])
        path = os.path.join(SHEET_DIR, f"{safe_name(name)}.csv")
        with open(path, "w", newline="") as out:
            writer = csv.writer(out)
            for row in rows:
                writer.writerow(row)
        inventory.append(
            (name, f"{safe_name(name)}.csv", sheet.get("totalRows", 0),
             sheet.get("totalCols", 0), sheet.get("truncated", False), len(rows))
        )

    # Rewrite the inventory README.
    lines = [
        "# Spreadsheet snapshot — `Material List - Hickory Master File`",
        "",
        f"Source: [{ss.get('name', '')}]({ss.get('url', '')})  ",
        f"Spreadsheet ID: `{ss.get('id', '')}`  ",
        f"Exported: {bundle.get('exportedAt', '')}",
        "",
        "Auto-generated by `scripts/split_export.py` from `reference/raw_export.json`.",
        "Each CSV holds a sheet's **displayed** values (formula results, not formulas).",
        "",
        "For what each sheet is *for*, see [`../docs/data-model.md`](../docs/data-model.md).",
        "",
        "| Sheet (CSV) | Total rows | Cols | Rows captured | Truncated |",
        "|-------------|-----------:|-----:|--------------:|:---------:|",
    ]
    for name, fname, tr, tc, trunc, captured in inventory:
        mark = "⚠️ yes" if trunc else "no"
        link = fname.replace(" ", "%20")
        lines.append(f"| [`{fname}`]({link}) | {tr:,} | {tc} | {captured:,} | {mark} |")
    lines.append("")
    with open(os.path.join(SHEET_DIR, "README.md"), "w") as out:
        out.write("\n".join(lines))

    print(f"Wrote {len(inventory)} sheet CSVs + README to spreadsheet/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
